import { CONFIDENCE_THRESHOLDS, INDICATOR_PERIODS, MINIMUM_CANDLES } from '../config/index.mjs';
import { prepareCandles } from '../data/candles.mjs';
import { calculateRsi, clamp, ema, momentumPercent, slopePercent } from '../indicators/index.mjs';
import { structureBias } from '../structure/index.mjs';
import { analyzeMTFSMC } from '../smc/index.mjs';

function neutralAnalysis(timeframe, reason) { return { timeframe, bias: 'NEUTRAL', confidence: 0, status: 'NEUTRAL', ema50: null, ema200: null, emaSlope: null, rsi: null, momentum: null, structure: 'NEUTRAL', reason, scoreParts: { ema: 'NEUTRAL', slope: 'NEUTRAL', rsi: 'NEUTRAL', momentum: 'NEUTRAL', structure: 'NEUTRAL' } }; }
export function analyzeCandles(candles, timeframe, expectedBias = null, options = {}) { const normalized = prepareCandles(candles, options); if (normalized.length < MINIMUM_CANDLES.analysis) return neutralAnalysis(timeframe, `Need at least ${MINIMUM_CANDLES.analysis} completed candles`); const closes = normalized.map((c) => c.close); const ema50 = ema(closes, INDICATOR_PERIODS.emaFast); const ema200 = ema(closes, INDICATOR_PERIODS.emaSlow); const fast = ema50.at(-1); const slow = ema200.at(-1); const slope = slopePercent(ema50); const rsi = calculateRsi(closes); const momentum = momentumPercent(closes, timeframe === '4H' ? INDICATOR_PERIODS.momentumRegime : INDICATOR_PERIODS.momentumDefault); const structure = structureBias(normalized); let bullish = 0; let bearish = 0; if (fast > slow) bullish += 24; else if (fast < slow) bearish += 24; if (slope > 0.05) bullish += 18; else if (slope < -0.05) bearish += 18; if (rsi >= 55 && rsi < 80) bullish += 18; else if (rsi <= 45 && rsi > 20) bearish += 18; if (momentum > 0.15) bullish += 16; else if (momentum < -0.15) bearish += 16; if (structure === 'BULLISH') bullish += 24; else if (structure === 'BEARISH') bearish += 24; const bias = Math.abs(bullish - bearish) < CONFIDENCE_THRESHOLDS.neutralDelta ? 'NEUTRAL' : bullish > bearish ? 'BULLISH' : 'BEARISH'; const confidence = bias === 'NEUTRAL' ? 0 : clamp(50 + Math.abs(bullish - bearish) / 2, 0, 100); const agrees = expectedBias && expectedBias !== 'NEUTRAL' && bias === expectedBias; const conflicts = expectedBias && expectedBias !== 'NEUTRAL' && bias !== 'NEUTRAL' && bias !== expectedBias; return { timeframe, bias, confidence, status: conflicts ? 'CONFLICT' : agrees ? 'CONFIRMED' : 'NEUTRAL', ema50: fast, ema200: slow, emaSlope: slope, rsi, momentum, structure, completedCandles: normalized.length, scoreParts: { ema: fast > slow ? 'BULLISH' : fast < slow ? 'BEARISH' : 'NEUTRAL', slope: slope > 0.05 ? 'BULLISH' : slope < -0.05 ? 'BEARISH' : 'NEUTRAL', rsi: rsi >= 55 && rsi < 80 ? 'BULLISH' : rsi <= 45 && rsi > 20 ? 'BEARISH' : 'NEUTRAL', momentum: momentum > 0.15 ? 'BULLISH' : momentum < -0.15 ? 'BEARISH' : 'NEUTRAL', structure } }; }
export function analyze4HCandles(candles, options = {}) { const analysis = analyzeCandles(candles, '4H', null, options); return { ...analysis, regime: analysis.bias }; }
export const analyze1HCandles = (candles, fourHourBias, options = {}) => analyzeCandles(candles, '1H', fourHourBias, options);
export const analyze15MCandles = (candles, fourHourBias, options = {}) => { const analysis = analyzeCandles(candles, '15M', fourHourBias, options); return { ...analysis, entry: analysis.status === 'CONFIRMED' ? (analysis.bias === 'BULLISH' ? 'LONG' : 'SHORT') : 'WAIT' }; };
export function calculateMTFConfidence(fourHour, oneHour, fifteenMinute) { if (fourHour.bias === 'NEUTRAL') return 0; if (oneHour.status === 'CONFLICT' || fifteenMinute.status === 'CONFLICT') return Math.min(CONFIDENCE_THRESHOLDS.conflictMaximum, Math.round(fourHour.confidence * 0.4)); if (oneHour.status !== 'CONFIRMED' || fifteenMinute.status !== 'CONFIRMED' || fifteenMinute.entry === 'WAIT') return Math.min(CONFIDENCE_THRESHOLDS.waitMaximum, Math.round(fourHour.confidence * 0.45)); const score = (fourHour.confidence * 0.4) + (oneHour.confidence * 0.3) + (fifteenMinute.confidence * 0.3); return Math.round(clamp(score, 0, 100)); }
export function decideMTFAction(fourHour, oneHour, fifteenMinute) { if (fourHour.bias === 'BULLISH' && oneHour.status === 'CONFIRMED' && fifteenMinute.entry === 'LONG') return 'LONG'; if (fourHour.bias === 'BEARISH' && oneHour.status === 'CONFIRMED' && fifteenMinute.entry === 'SHORT') return 'SHORT'; return 'WAIT'; }
export function analyzeMTF(fourHourCandles, oneHourCandles, fifteenMinuteCandles) { const fourHour = analyze4HCandles(fourHourCandles); const oneHour = analyze1HCandles(oneHourCandles, fourHour.bias); const fifteenMinute = analyze15MCandles(fifteenMinuteCandles, fourHour.bias); const smc = analyzeMTFSMC(fourHourCandles, oneHourCandles, fifteenMinuteCandles); return { fourHour, oneHour, fifteenMinute, smc, action: decideMTFAction(fourHour, oneHour, fifteenMinute), confidence: calculateMTFConfidence(fourHour, oneHour, fifteenMinute) }; }
