import { SIGNAL_REFRESH_MS, fetchCurrentSignals } from './app/signalData.mjs';
import { filterSignals, renderSignalCards } from './components/signals/center.mjs';

const elements = {
  app: document.querySelector('#app'),
};

const state = {
  signals: [],
  failures: [],
  actionFilter: 'ALL',
  symbolFilter: '',
};

function renderShell() {
  const isSignals = window.location.pathname === '/signals';
  elements.app.innerHTML = `
    <nav class="top-nav" aria-label="Primary navigation">
      <a class="brand" href="/">AURION</a>
      <div>
        <a class="${isSignals ? '' : 'active'}" href="/">Dashboard</a>
        <a class="${isSignals ? 'active' : ''}" href="/signals">Signals</a>
        <a href="#">Backtest</a>
        <a href="#">Signal History</a>
        <a href="#">Markets</a>
        <a href="#">Settings</a>
      </div>
    </nav>
    ${isSignals ? signalsPage() : dashboardPage()}
  `;
  document.querySelector('#refreshButton')?.addEventListener('click', loadSignals);
  document.querySelectorAll('[data-filter]').forEach((button) => button.addEventListener('click', () => {
    state.actionFilter = button.dataset.filter;
    renderSignalList();
  }));
  document.querySelector('#symbolFilter')?.addEventListener('input', (event) => {
    state.symbolFilter = event.target.value;
    renderSignalList();
  });
}

function dashboardPage() {
  return `<main><section class="hero"><div class="hero-copy"><div class="eyebrow">◉ Live crypto signal engine</div><h1>Real-time AI-style crypto signals from live Binance market data.</h1><p>Aurion refreshes prices, 15-minute candles, momentum, RSI, volume, and MTF structure from the existing domain signal engine.</p><div class="hero-actions"><button id="refreshButton" type="button">↻ Refresh live signals</button><span id="refreshStatus">Connecting to live market data...</span></div></div><aside class="pulse-panel"><div class="panel-title">▰ Market pulse</div><strong id="pulseBias">Neutral</strong><p id="pulseAverage">Waiting for live crypto data...</p><div class="pulse-grid"><div><span>LONG</span><b id="buyCount">0</b></div><div><span>SHORT</span><b id="sellCount">0</b></div><div><span>WAIT</span><b id="waitCount">0</b></div></div></aside></section><div id="error" class="error hidden"></div><section class="signals-header"><div><p class="eyebrow">⚡ Signal board</p><h2>Highest-confidence opportunities</h2></div><p>▣ Consumes existing AURION domain signals.</p></section><section id="signalsGrid" class="signals-grid" aria-live="polite"></section><footer>Signals are informational only, not financial advice. No order execution is available.</footer></main>`;
}

function signalsPage() {
  return `<main><section class="signals-hero"><div><p class="eyebrow">◎ Signals Center</p><h1>Inspect current AURION signals in detail.</h1><p>Signal data flows from market data through candles, indicators, structure, BOS/CHoCH, SMC, MTF, and the existing signal engine before it reaches this UI.</p></div><div class="hero-actions"><button id="refreshButton" type="button">↻ Refresh signals</button><span id="refreshStatus">Connecting to live market data...</span></div></section><div id="error" class="error hidden"></div><section class="filter-bar" aria-label="Signal filters"><div>${['ALL', 'LONG', 'SHORT', 'WAIT'].map((action) => `<button data-filter="${action}" type="button">${action}</button>`).join('')}</div><label><span>Symbol</span><input id="symbolFilter" type="search" placeholder="BTC, ETH, SOL..." /></label></section><section id="signalsGrid" class="signals-grid signals-center-grid" aria-live="polite"></section><footer>Signals are generated by the existing AURION engine. This page filters generated results only.</footer></main>`;
}

function renderSkeletons() {
  document.querySelector('#signalsGrid').innerHTML = Array.from({ length: 8 }, () => '<div class="signal-card skeleton"></div>').join('');
}

function renderSignalList() {
  const signals = filterSignals(state.signals, state.actionFilter, state.symbolFilter);
  document.querySelector('#signalsGrid').innerHTML = renderSignalCards(signals);
  document.querySelectorAll('[data-filter]').forEach((button) => button.classList.toggle('active', button.dataset.filter === state.actionFilter));
}

function renderPulse() {
  const signals = state.signals;
  const average = signals.length ? signals.reduce((sum, signal) => sum + signal.change24h, 0) / signals.length : 0;
  document.querySelector('#pulseBias').textContent = signals.filter((signal) => signal.action !== 'WAIT').length ? 'Aligned' : 'Wait';
  document.querySelector('#pulseAverage').textContent = `${average.toFixed(2)}% average 24h move across tracked assets`;
  document.querySelector('#buyCount').textContent = signals.filter((signal) => signal.action === 'LONG').length;
  document.querySelector('#sellCount').textContent = signals.filter((signal) => signal.action === 'SHORT').length;
  document.querySelector('#waitCount').textContent = signals.filter((signal) => signal.action === 'WAIT').length;
}

async function loadSignals() {
  const button = document.querySelector('#refreshButton');
  const status = document.querySelector('#refreshStatus');
  const errorBox = document.querySelector('#error');
  button.disabled = true;
  errorBox.classList.add('hidden');
  if (!document.querySelector('#signalsGrid').children.length) renderSkeletons();
  try {
    const result = await fetchCurrentSignals();
    state.signals = result.signals;
    state.failures = result.failures;
    if (!state.signals.length) throw new Error('Market-data unavailable: no current signals were returned from Binance.');
    renderSignalList();
    if (document.querySelector('#pulseBias')) renderPulse();
    status.textContent = `Updated ${new Date().toLocaleTimeString()} from shared Binance signal data${state.failures.length ? ` (${state.failures.length} symbols delayed)` : ''}`;
  } catch (error) {
    document.querySelector('#signalsGrid').innerHTML = '<div class="empty-state">No signals available.</div>';
    errorBox.textContent = error.message;
    errorBox.classList.remove('hidden');
    status.textContent = 'Network failure or market-data unavailable';
  } finally {
    button.disabled = false;
  }
}

renderShell();
loadSignals();
window.setInterval(loadSignals, SIGNAL_REFRESH_MS);
