import { prepareCandles } from '../data/candles.mjs';
import { generateSignal } from '../signals/engine.mjs';
import { MINIMUM_CANDLES, TIMEFRAMES } from '../config/index.mjs';

const MS = { '4h': 4 * 60 * 60 * 1000, '1h': 60 * 60 * 1000, '15m': 15 * 60 * 1000 };
export const DEFAULT_BACKTEST_OPTIONS = Object.freeze({ symbol: 'BTCUSDT', initialEquity: 10000, positionSize: 1000, feeRate: 0.001, slippageRate: 0.0005, stopLossPercent: 0.01, takeProfitPercent: 0.02, sameCandleRule: 'STOP_LOSS_FIRST' });

function assertUniqueChronological(raw, name) { if (!Array.isArray(raw)) throw new Error(`${name} candles must be an array`); for (let i = 1; i < raw.length; i += 1) { const prev = Number(raw[i - 1].time ?? raw[i - 1].openTime ?? raw[i - 1][0]); const cur = Number(raw[i].time ?? raw[i].openTime ?? raw[i][0]); if (cur < prev) throw new Error(`${name} candles must be chronological`); if (cur === prev) throw new Error(`${name} candles contain duplicate timestamps`); } }
function validateCompleted(candles, name, durationMs, now) { for (const c of candles) { const closeTime = c.closeTime ?? c.time + durationMs - 1; if (closeTime > now) throw new Error(`${name} contains an incomplete candle`); } }
function normalizeFrame(raw, name, durationMs, now) { assertUniqueChronological(raw, name); const candles = prepareCandles(raw, { now, excludeOpen: false }); validateCompleted(candles, name, durationMs, now); if (candles.length < MINIMUM_CANDLES.analysis) throw new Error(`${name} has insufficient history: need at least ${MINIMUM_CANDLES.analysis}`); return candles; }
function completedAt(candles, at, durationMs) { return candles.filter((c) => (c.closeTime ?? c.time + durationMs - 1) <= at); }
function assertAligned(candles, timeframe, durationMs) { for (let i = 1; i < candles.length; i += 1) if (candles[i].time - candles[i - 1].time !== durationMs) throw new Error(`${timeframe} candles have conflicting timeframe spacing`); }
const latest = (xs) => xs.at(-1) ?? null;
const summarize = (items) => items?.length ? latest(items) : null;
function signalRecord(signal, candle) { const smc = signal.smcConfirmation ?? signal.mtf?.smc; return { timestamp: candle.time, symbol: signal.rawSymbol ?? signal.symbol, action: signal.action, confidence: signal.confidence, entryPrice: candle.close, fourHourRegime: signal.mtf.fourHour.regime ?? signal.mtf.fourHour.bias, oneHourConfirmation: signal.mtf.oneHour.status, fifteenMinuteEntryState: signal.mtf.fifteenMinute.entry, bos: summarize(smc?.fifteenMinute?.bos), choch: summarize(smc?.fifteenMinute?.choch), liquidity: summarize(smc?.fifteenMinute?.liquiditySweeps), fvg: summarize(smc?.fifteenMinute?.fairValueGaps), orderBlock: summarize(smc?.fifteenMinute?.orderBlocks), reason: signal.reason, mtf: signal.mtf, smcConfirmation: smc }; }
function withSlippage(price, action, side, rate) { const adverse = (action === 'LONG' && side === 'entry') || (action === 'SHORT' && side === 'exit') ? 1 : -1; return price * (1 + adverse * rate); }
function openTrade(record, options) { const entry = withSlippage(record.entryPrice, record.action, 'entry', options.slippageRate); const sl = record.action === 'LONG' ? entry * (1 - options.stopLossPercent) : entry * (1 + options.stopLossPercent); const tp = record.action === 'LONG' ? entry * (1 + options.takeProfitPercent) : entry * (1 - options.takeProfitPercent); return { symbol: record.symbol, action: record.action, entryTime: record.timestamp, entryPrice: entry, stopLoss: sl, takeProfit: tp, exitTime: null, exitPrice: null, outcome: 'OPEN', pnl: 0, fees: Math.abs(options.positionSize) * options.feeRate } }
function closeTrade(trade, candle, reason, rawExit, options) { const exitPrice = withSlippage(rawExit, trade.action, 'exit', options.slippageRate); const qty = options.positionSize / trade.entryPrice; const gross = trade.action === 'LONG' ? (exitPrice - trade.entryPrice) * qty : (trade.entryPrice - exitPrice) * qty; const exitFee = Math.abs(qty * exitPrice) * options.feeRate; trade.exitTime = candle.time; trade.exitPrice = exitPrice; trade.outcome = reason; trade.fees += exitFee; trade.pnl = gross - trade.fees; return trade; }
function advanceTrade(trade, candle, options) { const hitSL = trade.action === 'LONG' ? candle.low <= trade.stopLoss : candle.high >= trade.stopLoss; const hitTP = trade.action === 'LONG' ? candle.high >= trade.takeProfit : candle.low <= trade.takeProfit; if (hitSL && hitTP) return closeTrade(trade, candle, 'SL_AMBIGUOUS', trade.stopLoss, options); if (hitSL) return closeTrade(trade, candle, 'SL', trade.stopLoss, options); if (hitTP) return closeTrade(trade, candle, 'TP', trade.takeProfit, options); return null; }
function metrics(trades, signals, initialEquity) { let equity = initialEquity, peak = initialEquity, maxDrawdown = 0, cw = 0, cl = 0, consecutiveWins = 0, consecutiveLosses = 0; const equityCurve = [{ timestamp: null, equity }]; for (const t of trades) { equity += t.pnl; peak = Math.max(peak, equity); maxDrawdown = Math.max(maxDrawdown, peak - equity); if (t.pnl > 0) { cw += 1; cl = 0; } else { cl += 1; cw = 0; } consecutiveWins = Math.max(consecutiveWins, cw); consecutiveLosses = Math.max(consecutiveLosses, cl); equityCurve.push({ timestamp: t.exitTime, equity }); } const wins = trades.filter((t) => t.pnl > 0), losses = trades.filter((t) => t.pnl <= 0); const grossProfit = wins.reduce((s,t)=>s+t.pnl,0), grossLoss = losses.reduce((s,t)=>s+t.pnl,0); const by = (a) => trades.filter((t)=>t.action===a); const perf = (arr) => ({ trades: arr.length, wins: arr.filter(t=>t.pnl>0).length, losses: arr.filter(t=>t.pnl<=0).length, netPnl: arr.reduce((s,t)=>s+t.pnl,0) }); return { totalSignals: signals.length, totalTrades: trades.length, winningTrades: wins.length, losingTrades: losses.length, winRate: trades.length ? wins.length / trades.length : 0, grossProfit, grossLoss, netPnl: grossProfit + grossLoss, averageTrade: trades.length ? (grossProfit + grossLoss) / trades.length : 0, profitFactor: grossLoss === 0 ? (grossProfit > 0 ? Infinity : 0) : grossProfit / Math.abs(grossLoss), maxDrawdown, consecutiveWins, consecutiveLosses, longPerformance: perf(by('LONG')), shortPerformance: perf(by('SHORT')), equityCurve }; }

export async function runBacktest(input = {}) { const options = { ...DEFAULT_BACKTEST_OPTIONS, ...input }; const now = options.now ?? Number.MAX_SAFE_INTEGER; const fourHour = normalizeFrame(input.fourHourCandles ?? [], '4H', MS['4h'], now); const oneHour = normalizeFrame(input.oneHourCandles ?? [], '1H', MS['1h'], now); const fifteen = normalizeFrame(input.fifteenMinuteCandles ?? [], '15M', MS['15m'], now); if (options.strictSpacing) { assertAligned(fourHour, '4H', MS['4h']); assertAligned(oneHour, '1H', MS['1h']); assertAligned(fifteen, '15M', MS['15m']); } const period = { start: fifteen[0].time, end: fifteen.at(-1).time, partitions: options.partitions ?? null }; const signals = [], trades = []; let open = null; for (const candle of fifteen) { if (open && candle.time > open.entryTime) { const closed = advanceTrade(open, candle, options); if (closed) { trades.push(closed); open = null; } } const at = candle.closeTime ?? candle.time + MS['15m'] - 1; const f4 = completedAt(fourHour, at, MS['4h']); const h1 = completedAt(oneHour, at, MS['1h']); const m15 = completedAt(fifteen, at, MS['15m']); if (f4.length < MINIMUM_CANDLES.analysis || h1.length < MINIMUM_CANDLES.analysis || m15.length < MINIMUM_CANDLES.analysis) continue; const provider = { getTicker: async () => ({ lastPrice: String(candle.close), priceChangePercent: '0', quoteVolume: String(candle.volume) }), getCandles: async (_symbol, tf) => tf === TIMEFRAMES.REGIME ? f4 : tf === TIMEFRAMES.SETUP ? h1 : m15 }; const signal = await generateSignal(options.symbol, { marketDataProvider: provider, timestamp: candle.time }); const record = signalRecord(signal, candle); signals.push(record); if (!open && record.action !== 'WAIT') open = openTrade(record, options); } return { symbol: options.symbol, period, options: { feeRate: options.feeRate, slippageRate: options.slippageRate, stopLossPercent: options.stopLossPercent, takeProfitPercent: options.takeProfitPercent, sameCandleRule: options.sameCandleRule }, signals, trades, metrics: metrics(trades, signals, options.initialEquity) }; }

export function formatBacktestReport(result) { const m = result.metrics; return `AURION BACKTEST\n----------------\nPeriod: ${new Date(result.period.start).toISOString()} - ${new Date(result.period.end).toISOString()}\nSymbol: ${result.symbol}\nSignals: ${m.totalSignals}\nTrades: ${m.totalTrades}\nWin rate: ${(m.winRate * 100).toFixed(2)}%\nNet P&L: ${m.netPnl.toFixed(2)}\nProfit factor: ${Number.isFinite(m.profitFactor) ? m.profitFactor.toFixed(2) : 'Infinity'}\nMax drawdown: ${m.maxDrawdown.toFixed(2)}\nLONG: ${m.longPerformance.trades} trades / ${m.longPerformance.netPnl.toFixed(2)} P&L\nSHORT: ${m.shortPerformance.trades} trades / ${m.shortPerformance.netPnl.toFixed(2)} P&L`; }
